entry-points:
  # Master Sword Restricted
  master-sword-restricted: msr
  msr: msr3
  msr3: /routes/msr3/project.yaml

  # All Shrines
  all-shrines: as
  as: as4
  as4: as45
  as45: /routes/as4/project.yaml

  all-shrines-b: as-b
  as-b: as4-b
  as4-b: /routes/as4b/project.yaml

  # All Shrines EX
  all-shrines-extended: asx
  all-shrines-ex: asx
  asx: asx4
  asx4: /routes/asx4/project.yaml

  # Hundo EX
  1ex: 1x
  100x: 1x
  hundo-ex: 1x
  1x: 1x6
  1x6: /routes/1x6/project.yaml

  ### Extensions ###
  all-quests: aq
  aq: aq2
  aq2: /routes/aq2/project.yaml

  # All Goddess Statues Restricted
  all-goddess-statues-restricted: agsr
  agsr: /routes/agsr/project.yaml